baseurl: "/me"
url: "https://santimanuelr.github.io"
title: Santi Rodr√≠guez
description: Fullstack developer.
show_downloads: false
google_analytics: G-KV81561R24
theme: jekyll-theme-hacker
url_linkedin: https://ar.linkedin.com/in/santimanuelr
mail: mailto:santimanuelr@gmail.com
